name: Deploy Hugo site to Pages

on:
  # Runs on pushes to the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permission to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.126.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (if using submodules)
          fetch-depth: 0    # Fetch all history for .GitInfo and other things

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          # extended: true # If you are using SCSS, change this to 'true'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Run Hugo
        env:
          # This environment variable tells the Hugo action to override the baseURL
          # Replace <YOUR_USERNAME> with your actual GitHub username
          # Replace <YOUR_REPO_NAME> with your actual repository name
          # Using dynamic variables from GitHub Context for robustness
          HUGO_BASEURL: "https://${{ github.actor }}.github.io/${{ github.event.repository.name }}/"
        run: hugo --minify --cleanDestinationDir # Add --minify and --cleanDestinationDir for best practice

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire `public` folder
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2